(() => {
  const pick=a=>a[Math.floor(Math.random()*a.length)];
  const round=(n,p=1)=>{const f=10**p;return Math.round((Number(n)+Number.EPSILON)*f)/f};
  const randInt=(min,max,step=1)=>min+Math.floor(Math.random()*(Math.floor((max-min)/step)+1))*step;
  const randDec=(min,max,p=1)=>round(min+Math.random()*(max-min),p);
  let currentDifficulty='standard';
  const difficulty=()=>currentDifficulty;
  const byDifficulty=(easy,standard,challenge)=>difficulty()==='easy'?easy:difficulty()==='challenge'?challenge:standard;
  const q=(key,type,prompt,answer,unit,formula,note,solution,tolerance=.05,vars={})=>({key,type,prompt,answer,unit,formula,note,solution,tolerance,vars});

  const basicPools={
    easy:[
      ['acetaminophen',325,325,1,'tablet','PO'],['acetaminophen',650,325,1,'tablets','PO'],
      ['amoxicillin',250,250,5,'mL','PO'],['amoxicillin',500,250,5,'mL','PO'],
      ['cephalexin',250,250,5,'mL','PO'],['cephalexin',500,250,5,'mL','PO'],
      ['ondansetron',4,4,2,'mL','IV'],['furosemide',20,20,2,'mL','IV'],['furosemide',40,20,2,'mL','IV'],
      ['diphenhydramine',25,50,1,'mL','IV'],['diphenhydramine',50,50,1,'mL','IV'],
      ['dexamethasone',4,4,1,'mL','IV'],['ketorolac',15,15,1,'mL','IV'],['ketorolac',30,30,1,'mL','IV'],
      ['famotidine',20,10,1,'mL','IV'],['metoclopramide',10,5,1,'mL','IV'],['prednisone',10,10,1,'tablet','PO'],['prednisone',20,10,1,'tablets','PO']
    ],
    standard:[
      ['acetaminophen',325,325,1,'tablet','PO'],['acetaminophen',650,325,1,'tablets','PO'],
      ['amoxicillin',250,125,5,'mL','PO'],['amoxicillin',500,125,5,'mL','PO'],['amoxicillin',250,250,5,'mL','PO'],['amoxicillin',500,250,5,'mL','PO'],
      ['cephalexin',250,125,5,'mL','PO'],['cephalexin',500,125,5,'mL','PO'],['cephalexin',250,250,5,'mL','PO'],['cephalexin',500,250,5,'mL','PO'],
      ['ondansetron',4,4,2,'mL','IV'],
      ['furosemide',20,20,2,'mL','IV'],['furosemide',40,20,2,'mL','IV'],['furosemide',80,20,2,'mL','IV'],
      ['diphenhydramine',10,50,1,'mL','IV'],['diphenhydramine',25,50,1,'mL','IV'],['diphenhydramine',50,50,1,'mL','IV'],
      ['dexamethasone',4,4,1,'mL','IV'],['dexamethasone',8,4,1,'mL','IV'],['dexamethasone',10,10,1,'mL','IV'],
      ['ketorolac',15,15,1,'mL','IV'],['ketorolac',15,30,1,'mL','IV'],['ketorolac',30,30,1,'mL','IV'],
      ['famotidine',10,10,1,'mL','IV'],['famotidine',20,10,1,'mL','IV'],
      ['metoclopramide',5,5,1,'mL','IV'],['metoclopramide',10,5,1,'mL','IV'],
      ['prednisone',10,10,1,'tablet','PO'],['prednisone',20,10,1,'tablets','PO'],['prednisone',30,10,1,'tablets','PO'],['prednisone',40,10,1,'tablets','PO']
    ],
    challenge:[
      ['amoxicillin',375,250,5,'mL','PO'],['amoxicillin',625,250,5,'mL','PO'],
      ['cephalexin',375,250,5,'mL','PO'],['cephalexin',375,125,5,'mL','PO'],
      ['diphenhydramine',12.5,50,1,'mL','IV'],['diphenhydramine',37.5,50,1,'mL','IV'],
      ['dexamethasone',6,4,1,'mL','IV'],['dexamethasone',7.5,10,1,'mL','IV'],
      ['famotidine',15,10,1,'mL','IV'],['metoclopramide',7.5,5,1,'mL','IV'],
      ['ketorolac',15,30,1,'mL','IV'],['prednisone',12.5,10,1,'tablets','PO'],['prednisone',17.5,10,1,'tablets','PO'],['prednisone',27.5,10,1,'tablets','PO']
    ]
  };
  const weightTemplates={
    easy:[['acetaminophen',15,'PO per dose',12,35],['gentamicin',1.5,'IV q8h',45,85],['enoxaparin',1,'subcutaneous q12h',50,100]],
    standard:[['acetaminophen',15,'PO per dose',12,35],['clindamycin',10,'IV per dose',18,45],['vancomycin',15,'IV per dose',40,95],['gentamicin',1.5,'IV q8h',45,90],['enoxaparin',1,'subcutaneous q12h',50,110]],
    challenge:[['clindamycin',12.5,'IV per dose',18,45],['vancomycin',17.5,'IV per dose',40,95],['gentamicin',1.7,'IV q8h',45,90],['enoxaparin',1,'subcutaneous q12h',50,110]]
  };
  const pedsRanges=[
    {drug:'cephalexin',context:'routine pediatric infection',minDay:25,maxDay:50,have:[125,250],qty:5,freqs:[['q6h',4],['q12h',2]]},
    {drug:'cephalexin',context:'severe pediatric infection',minDay:50,maxDay:100,have:[125,250],qty:5,freqs:[['q6h',4],['q12h',2]]},
    {drug:'clindamycin',context:'serious pediatric infection',minDay:8,maxDay:12,have:[75],qty:5,freqs:[['q6h',4],['q8h',3]]},
    {drug:'clindamycin',context:'severe pediatric infection',minDay:13,maxDay:16,have:[75],qty:5,freqs:[['q6h',4],['q8h',3]]},
    {drug:'clindamycin',context:'more severe pediatric infection',minDay:17,maxDay:25,have:[75],qty:5,freqs:[['q6h',4],['q8h',3]]}
  ];
  const ivFluids=['0.9% sodium chloride','lactated Ringer’s','D5W','D5 0.45% sodium chloride'];

  function basicDose(){const [drug,order,have,qty,unit,route]=pick(basicPools[difficulty()]),a=round(order/have*qty,2);return q('basic-dose','Basic medication dose',`A patient has an order for ${drug} ${order} mg ${route}. Available: ${have} mg per ${qty} ${unit}. How many ${unit} should the nurse administer?`,a,unit,'Desired dose ÷ dose on hand × quantity = amount to give','Use the labeled concentration and keep the requested final unit.',`(${order} mg ÷ ${have} mg) × ${qty} ${unit} = ${a} ${unit}`,.06,{drug,order,have,qty,unit,route})}
  function weightDose(){const [drug,dose,route,min,max]=pick(weightTemplates[difficulty()]),kg=difficulty()==='easy'?randInt(min,max):randDec(min,max,1),a=round(kg*dose,1);return q('weight-dose','Weight-based dose',`A ${kg}-kg patient is prescribed ${drug} ${dose} mg/kg/dose ${route}. How many mg should the patient receive per dose?`,a,'mg','mg/kg/dose × kg = mg per dose','Cancel kg and report the medication dose in mg.',`${dose} mg/kg × ${kg} kg = ${a} mg/dose`,.06,{drug,kg,dose,route})}
  function pedsSafe(){const t=pick(pedsRanges),[freq,doses]=pick(t.freqs),kg=difficulty()==='easy'?randInt(12,32):randDec(11.5,34.5,1),have=pick(t.have),min=round(kg*t.minDay/doses,1),max=round(kg*t.maxDay/doses,1),target=pick(['low','safe','high']);let order;if(target==='low')order=Math.max(5,Math.round((min-Math.max(5,min*.15))/5)*5);else if(target==='high')order=Math.round((max+Math.max(5,max*.15))/5)*5;else order=Math.round(randDec(min,max,1)/5)*5;const safety=order<min?'too low':order>max?'too high':'safe',ml=round(order*t.qty/have,1);return q('peds-safe-range','Pediatric safe-dose range',`A child weighs ${kg} kg and is being treated for a ${t.context}. The provider orders ${t.drug} ${order} mg PO ${freq}. Recommended: ${t.minDay}–${t.maxDay} mg/kg/day in equally divided doses. Available: ${have} mg/${t.qty} mL. Is the ordered dose safe, too low, or too high?`,safety,'','mg/kg/day × kg ÷ doses/day = safe mg/dose range','Find both ends of the per-dose range before comparing the provider order. Calculate mL only if the dose is safe.',`Safe range: ${min}–${max} mg/dose. Order ${order} mg is ${safety}.${safety==='safe'?` Amount: (${order} ÷ ${have}) × ${t.qty} = ${ml} mL.`:''}`,.05,{drug:t.drug,context:t.context,kg,order,freq,doses,minDay:t.minDay,maxDay:t.maxDay,have,qty:t.qty,min,max,ml,safety})}
  function mlhr(){const v=pick([100,150,250,500,1000]),h=pick(byDifficulty([2,4,5,8],[1.5,2.25,3.5,4.5,5.5,6.5,7.5,8],[1.8,2.7,3.75,4.6,5.25,6.8,7.25])),fluid=pick(ivFluids),a=round(v/h,1);return q('mlhr-hours','mL/hr — hours',`${fluid}, ${v} mL, is prescribed to infuse over ${h} hours. What rate should the IV pump be programmed to?`,a,'mL/hr','mL ÷ hours = mL/hr','Volume divided by infusion time gives the pump rate.',`${v} mL ÷ ${h} hr = ${a} mL/hr`,.05,{volume:v,hours:h,fluid})}
  function mlhrMin(){const [drug,v]=pick([['ceftriaxone',50],['metronidazole',100],['clindamycin',100],['vancomycin',250],['magnesium sulfate loading dose',100]]),m=pick(byDifficulty([30,60,90],[30,40,45,50,60,75,90,105,120],[37,43,47,53,67,83,97,107])),a=round(v/(m/60),1);return q('mlhr-minutes','mL/hr — minutes',`${drug} in ${v} mL IV is ordered to infuse over ${m} minutes. What pump rate is required?`,a,'mL/hr','mL ÷ (minutes ÷ 60) = mL/hr','Convert the prescribed minutes to hours before dividing.',`${m} min ÷ 60 = ${round(m/60,2)} hr; ${v} mL ÷ ${round(m/60,2)} hr = ${a} mL/hr`,.05,{drug,volume:v,minutes:m})}
  function duration(){const v=pick([100,250,500,1000]),r=pick(byDifficulty([50,75,100,125,200],[72,83,92,108,115,123,137,150],[67,79,87,113,117,129,143])),fluid=pick(ivFluids),a=round(v/r,2);return q('infusion-time','Infusion duration',`${fluid}, ${v} mL, is infusing at ${r} mL/hr. How many hours will the infusion take?`,a,'hours','mL ÷ mL/hr = hours','The mL units cancel, leaving hours.',`${v} mL ÷ ${r} mL/hr = ${a} hr`,.02,{volume:v,rate:r,fluid})}
  function completion(){const start=`${String(randInt(0,23)).padStart(2,'0')}:${String(pick([0,5,10,15,20,25,30,35,40,45,50,55])).padStart(2,'0')}`,v=pick([100,250,500,1000]),r=pick(byDifficulty([50,100,125,200],[72,83,92,108,115,123,137],[67,79,87,93,113,117,129])),fluid=pick(ivFluids),mins=Math.round(v/r*60),[hh,mm]=start.split(':').map(Number),end=(hh*60+mm+mins)%1440,ans=`${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`;return q('completion-time','Completion time',`${fluid}, ${v} mL, starts at ${start} and infuses at ${r} mL/hr. Using 24-hour time, when will it finish?`,ans,'','(mL ÷ mL/hr) → infusion time; then add to start time','Find the infusion duration first, convert it to hours/minutes, then add it to the clock time.',`${v} ÷ ${r} = ${round(v/r,2)} hr ≈ ${mins} min; ${start} + ${mins} min = ${ans}`,0,{start,v,r,fluid})}
  function gtt(){const v=pick([100,250,500,1000]),h=pick(byDifficulty([2,4,5,8],[1.5,2.25,3.5,4.5,5.5,7.5],[1.8,2.7,3.75,4.6,5.25,7.25])),d=pick([10,15,20,60]),fluid=pick(ivFluids),a=Math.round(v*d/(h*60));return q('gtt-volume-time','gtt/min — volume + time',`${fluid}, ${v} mL, is prescribed over ${h} hours using tubing with a drop factor of ${d} gtt/mL. Calculate gtt/min.`,a,'gtt/min','(mL × gtt/mL) ÷ total minutes = gtt/min','Convert hours to minutes and round the final answer to a whole drop.',`(${v} × ${d}) ÷ (${h} × 60) = ${a} gtt/min`,.05,{volume:v,hours:h,dropFactor:d,fluid})}
  function gttFromMlhr(){const r=pick(byDifficulty([50,75,100,125,150],[72,83,92,108,117,123,137],[67,79,89,113,127,143])),d=pick([10,15,20,60]),fluid=pick(ivFluids),a=Math.round(r*d/60);return q('gtt-from-mlhr','mL/hr → gtt/min',`${fluid} is infusing at ${r} mL/hr using tubing with a drop factor of ${d} gtt/mL. What gravity flow rate should be set?`,a,'gtt/min','(mL/hr × gtt/mL) ÷ 60 min/hr = gtt/min','Convert the hourly flow into drops per minute.',`(${r} × ${d}) ÷ 60 = ${a} gtt/min`,.05,{rate:r,dropFactor:d,fluid})}
  function mlhrFromGtt(){const g=pick(byDifficulty([15,20,25,30,40,50],[17,19,23,27,31,37,43,47],[13,17,23,29,31,41,47,53])),d=pick([10,15,20,60]),fluid=pick(ivFluids),a=round(g*60/d,1);return q('mlhr-from-gtt','gtt/min → mL/hr',`${fluid} is running at ${g} gtt/min through tubing with a drop factor of ${d} gtt/mL. What is the equivalent mL/hr rate?`,a,'mL/hr','(gtt/min × 60 min/hr) ÷ gtt/mL = mL/hr','Convert drops per minute to drops per hour, then divide by the drop factor.',`(${g} × 60) ÷ ${d} = ${a} mL/hr`,.05,{dropsPerMinute:g,dropFactor:d,fluid})}
  function reconstitution(){const t=pick(byDifficulty([{drug:'ampicillin',conc:250,orders:[250,500,750]}],[{drug:'cefazolin',conc:330,orders:[495,660,825,990]},{drug:'methylprednisolone',conc:62.5,orders:[62.5,75,93.75,125]},{drug:'ampicillin',conc:250,orders:[375,500,625,750]}],[{drug:'cefazolin',conc:330,orders:[550,715,775,935]},{drug:'methylprednisolone',conc:62.5,orders:[68.75,81.25,87.5,106.25]},{drug:'ampicillin',conc:250,orders:[425,575,675]}])),order=pick(t.orders),a=round(order/t.conc,2);return q('reconstitution','Reconstitution',`After reconstitution, ${t.drug} is labeled ${t.conc} mg/mL. The provider orders ${order} mg. How many mL should the nurse withdraw from the reconstituted vial?`,a,'mL','ordered mg ÷ final concentration (mg/mL) = mL to withdraw','Use the concentration after reconstitution, not the dry-vial amount.',`${order} mg ÷ ${t.conc} mg/mL = ${a} mL`,.03,{drug:t.drug,order,conc:t.conc})}
  function unitsHr(){const insulin=Math.random()<.3,c=insulin?{drug:'regular insulin',order:difficulty()==='easy'?randInt(2,10):randDec(2,10,1),bagUnits:100,bagMl:100}:{drug:'heparin',order:difficulty()==='easy'?randInt(800,1800,100):randInt(825,1775,25),bagUnits:25000,bagMl:500},conc=c.bagUnits/c.bagMl,a=round(c.order/conc,1);return q('units-hour','Units/hr infusion',`A patient is receiving ${c.drug} at ${c.order} units/hr. The IV contains ${c.bagUnits.toLocaleString()} units in ${c.bagMl} mL. What pump rate is required?`,a,'mL/hr','ordered units/hr ÷ concentration (units/mL) = mL/hr','First find units per mL in the bag.',`${c.bagUnits} ÷ ${c.bagMl} = ${round(conc,2)} units/mL; ${c.order} ÷ ${round(conc,2)} = ${a} mL/hr`,.05,c)}
  function mcgMin(){const norepi=Math.random()<.4,c=norepi?{drug:'norepinephrine',order:difficulty()==='easy'?pick([2,4,8,12]):randInt(2,12,1),bagMcg:4000,bagMl:250}:{drug:'nitroglycerin',order:difficulty()==='easy'?pick([10,20,40,60,80]):randInt(10,120,5),bagMcg:50000,bagMl:250},conc=c.bagMcg/c.bagMl,a=round(c.order*60/conc,1);return q('mcg-minute','mcg/min infusion',`A patient is prescribed ${c.drug} ${c.order} mcg/min. The IV contains ${c.bagMcg.toLocaleString()} mcg in ${c.bagMl} mL. What pump rate is required?`,a,'mL/hr','(mcg/min × 60 min/hr) ÷ concentration (mcg/mL) = mL/hr','Convert the ordered dose to mcg/hr, then divide by the bag concentration.',`${c.order} × 60 = ${c.order*60} mcg/hr; ${c.bagMcg} ÷ ${c.bagMl} = ${round(conc,2)} mcg/mL; ${c.order*60} ÷ ${round(conc,2)} = ${a} mL/hr`,.05,c)}
  function mcgKgMin(){const t=pick([{drug:'dopamine',doseMin:2,doseMax:10,bagMcg:400000},{drug:'dobutamine',doseMin:2.5,doseMax:15,bagMcg:250000}]),kg=difficulty()==='easy'?randInt(50,90,5):randDec(48,92,1),dose=difficulty()==='easy'?pick(t.drug==='dopamine'?[2,5,10]:[2.5,5,7.5,10,12.5,15]):randDec(t.doseMin,t.doseMax,1),c={drug:t.drug,kg,dose,bagMcg:t.bagMcg,bagMl:250},conc=c.bagMcg/c.bagMl,a=round(c.dose*c.kg*60/conc,1);return q('mcg-kg-minute','mcg/kg/min infusion',`A ${c.kg}-kg patient is prescribed ${c.drug} ${c.dose} mcg/kg/min. The IV contains ${c.bagMcg.toLocaleString()} mcg in ${c.bagMl} mL. What pump rate is required?`,a,'mL/hr','(mcg/kg/min × kg × 60 min/hr) ÷ concentration (mcg/mL) = mL/hr','Cancel kg first, convert the minute dose to an hourly dose, then divide by concentration.',`${c.dose} × ${c.kg} × 60 = ${round(c.dose*c.kg*60,2)} mcg/hr; ÷ ${round(conc,2)} mcg/mL = ${a} mL/hr`,.05,c)}
  function amountRate(){if(Math.random()<.5){const order=pick([0.5,1]),bag=pick([{amt:900,ml:500},{amt:450,ml:250}]),hourly=order*60,conc=bag.amt/bag.ml,a=round(hourly/conc,1);return q('amount-hour','Rate-based infusion (mg/min or g/hr)',`Amiodarone is ordered at ${order} mg/min. The IV contains ${bag.amt} mg in ${bag.ml} mL. What pump rate is required?`,a,'mL/hr','(mg/min × 60 min/hr) ÷ concentration (mg/mL) = mL/hr','Amiodarone is ordered per minute, so convert the dose to mg/hr before calculating mL/hr.',`${order} × 60 = ${hourly} mg/hr; ${bag.amt} ÷ ${bag.ml} = ${round(conc,2)} mg/mL; ${hourly} ÷ ${round(conc,2)} = ${a} mL/hr`,.05,{drug:'amiodarone',order,orderUnit:'mg/min',bagAmt:bag.amt,bagMl:bag.ml})}const order=pick([1,1.5,2]),bag=pick([{amt:20,ml:500},{amt:40,ml:1000}]),conc=bag.amt/bag.ml,a=round(order/conc,1);return q('amount-hour','Rate-based infusion (mg/min or g/hr)',`Magnesium sulfate is ordered at ${order} g/hr by continuous IV infusion. The IV contains ${bag.amt} g in ${bag.ml} mL. What pump rate is required?`,a,'mL/hr','ordered g/hr ÷ concentration (g/mL) = mL/hr','The order is already per hour, so no time conversion is needed.',`${bag.amt} ÷ ${bag.ml} = ${round(conc,4)} g/mL; ${order} ÷ ${round(conc,4)} = ${a} mL/hr`,.05,{drug:'magnesium sulfate',order,orderUnit:'g/hr',bagAmt:bag.amt,bagMl:bag.ml})}
  function meqMl(){const t=pick([{drug:'potassium chloride',conc:2,kind:'additive'},{drug:'potassium acetate',conc:2,kind:'additive'},{drug:'sodium bicarbonate',conc:1,kind:'dose'}]),order=difficulty()==='easy'?randInt(10,40,5):randDec(10,40,1),a=round(order/t.conc,1),prompt=t.kind==='additive'?`The provider orders ${t.drug} ${order} mEq to be added to a compatible IV solution. The concentrate contains ${t.conc} mEq/mL. How many mL of concentrate should be withdrawn for the admixture?`:`The provider orders sodium bicarbonate ${order} mEq IV. The solution contains ${t.conc} mEq/mL. How many mL contain the ordered dose?`,note=t.kind==='additive'?'Potassium concentrate must be diluted in IV fluid; this question calculates the additive volume, not an IV-push dose.':'Divide the ordered mEq by the labeled mEq per mL.';return q('meq-ml','mEq to mL',prompt,a,'mL','ordered mEq ÷ concentration (mEq/mL) = mL',note,`${order} mEq ÷ ${t.conc} mEq/mL = ${a} mL`,.05,{drug:t.drug,order,conc:t.conc,kind:t.kind})}
  function dailyDivided(){const t=pick([{drug:'cephalexin',daily:25,doses:4,freq:'q6h'},{drug:'cephalexin',daily:50,doses:4,freq:'q6h'},{drug:'clindamycin',daily:12,doses:3,freq:'q8h'},{drug:'clindamycin',daily:24,doses:4,freq:'q6h'},{drug:'cefuroxime axetil',daily:20,doses:2,freq:'q12h'},{drug:'cefuroxime axetil',daily:30,doses:2,freq:'q12h'}]),kg=difficulty()==='easy'?randInt(12,32):randDec(11.5,34.5,1),day=round(t.daily*kg,1),a=round(day/t.doses,1);return q('daily-divided','Daily divided dose',`A ${kg}-kg child is prescribed ${t.drug} ${t.daily} mg/kg/day divided ${t.freq}. How many mg should be given per dose?`,a,'mg/dose','mg/kg/day × kg ÷ doses/day = mg/dose','Calculate the total daily dose, then divide by the number of scheduled doses in 24 hours.',`${t.daily} × ${kg} = ${day} mg/day; ${day} ÷ ${t.doses} = ${a} mg/dose`,.05,{drug:t.drug,kg,daily:t.daily,doses:t.doses,freq:t.freq})}

  const defs=[
    ['basic-dose','Basic medication dose',basicDose],['weight-dose','Weight-based dose',weightDose],['peds-safe-range','Pediatric safe-dose range',pedsSafe],
    ['mlhr-hours','mL/hr — hours',mlhr],['mlhr-minutes','mL/hr — minutes',mlhrMin],['infusion-time','Infusion duration',duration],['completion-time','Completion time',completion],
    ['gtt-volume-time','gtt/min — volume + time',gtt],['gtt-from-mlhr','mL/hr → gtt/min',gttFromMlhr],['mlhr-from-gtt','gtt/min → mL/hr',mlhrFromGtt],
    ['reconstitution','Reconstitution',reconstitution],['units-hour','Units/hr infusion',unitsHr],['mcg-minute','mcg/min infusion',mcgMin],['mcg-kg-minute','mcg/kg/min infusion',mcgKgMin],['amount-hour','Rate-based infusion (mg/min or g/hr)',amountRate],['meq-ml','mEq to mL',meqMl],['daily-divided','Daily divided dose',dailyDivided]
  ].map(([key,label,random])=>({key,label,random}));
  const byKey=Object.fromEntries(defs.map(x=>[x.key,x]));
  const formulaReview=[
    ['Basic medication dose','Desired ÷ Have × Quantity = amount to give'],['Weight-based dose','mg/kg/dose × kg = mg per dose'],['Pediatric safe-dose range','mg/kg/day × kg ÷ doses/day = safe mg/dose range'],
    ['Pump rate — hours','mL ÷ hours = mL/hr'],['Pump rate — minutes','mL ÷ (minutes ÷ 60) = mL/hr'],['Infusion duration','mL ÷ mL/hr = hours'],['Completion time','Find infusion duration, then add it to the start time'],
    ['Gravity flow','(mL × gtt/mL) ÷ total minutes = gtt/min'],['mL/hr → gtt/min','(mL/hr × gtt/mL) ÷ 60 = gtt/min'],['gtt/min → mL/hr','(gtt/min × 60) ÷ gtt/mL = mL/hr'],
    ['Reconstitution','ordered mg ÷ final concentration mg/mL = mL'],['Units/hr infusion','ordered units/hr ÷ units/mL = mL/hr'],['mcg/min infusion','(mcg/min × 60) ÷ mcg/mL = mL/hr'],['mcg/kg/min infusion','(mcg/kg/min × kg × 60) ÷ mcg/mL = mL/hr'],
    ['Rate-based infusion','Match the medication order time unit first, then divide by concentration'],['mEq to mL','ordered mEq ÷ mEq/mL = mL'],['Daily divided dose','mg/kg/day × kg ÷ doses/day = mg/dose']
  ];
  function generate(key,d='standard'){currentDifficulty=['easy','standard','challenge'].includes(d)?d:'standard';const def=byKey[key];if(!def)throw new Error(`Unknown dosage type: ${key}`);return def.random()}
  window.DosageEngine={version:2,types:defs.map(({key,label})=>({key,label})),formulaReview,generate,round};
})();
